### ISSUE TITLE
Ops generator generates wrong constant names

### ISSUE THREAD

**Issue by kalsan** [sitrox/rails_ops#30]
`rails g operation foos` generates files like `app/operations/foos/create.rb` that contain constants like `Operations::Foo::Create`.

The middle namespace should be `Foos`, not `Foo`. Same with the operation constant names generated for the controller.

The opposite happens in the generated operations: `hsh? :foos` instead of `hsh? :foo` is generated for Create and Update.

Note: tested with two words, e.g. FooBar/foo_bar

**Comment by sudoremo** [comment]
Thanks for the issue. Fixed with commit https://github.com/sitrox/rails_ops/commit/b3f8fa6a00245187774e6a83d75e2380e22afff6 and released with `1.4.2`.
